# Generated by Django 4.2.23 on 2025-07-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_order_address_order_admin_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Extra shipping charge set by admin",
                max_digits=10,
            ),
        ),
    ]
