# Generated by Django 4.2.23 on 2025-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_order_shipping_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_charge",
            field=models.IntegerField(default=0),
        ),
    ]
