# Generated by Django 4.2.23 on 2025-07-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Available quantity in stock"
            ),
        ),
    ]
