# Generated by Django 4.2.7 on 2025-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                choices=[("Orane", "Orane"), ("Klassy", "Klassy")],
                default="Orane",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Discount percentage (e.g., 79 for 79%)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discounted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Price after discount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="MRP (Original Price)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
